@baseUrl = http://localhost:3000
@contentType = application/json
@import config.http

# @name createAdmin
POST {{baseUrl}}/api/admin/create
Authorization: Bearer {{global.token}}
Content-Type: {{contentType}}

{
  "email": "newadmin@logiquest.dev",
  "password": "Admin123!",
  "role": "admin"
}

### Check admin access Check admin access
# @name checkAdminAccess# @name checkAdminAccess
GET {{baseUrl}}/api/admin/admin
Authorization: Bearer {{global.token}}ken}}
Content-Type: {{contentType}}

### Update admin### Update admin
# @name updateAdmin @name updateAdmin
PATCH {{baseUrl}}/api/admin/1
Authorization: Bearer {{global.token}}}}
Content-Type: {{contentType}}ontentType}}

{{
  "email": "updated@logiquest.dev",email": "updated@logiquest.dev",
  "password": "UpdatedAdmin123!"  "password": "UpdatedAdmin123!"
}

### Delete admin
# @name deleteAdmin
DELETE {{baseUrl}}/api/admin/1DELETE {{baseUrl}}/api/admin/1
Authorization: Bearer {{global.token}}uthorization: Bearer {{global.token}}
Content-Type: {{contentType}}