#Create a user 

POST http://localhost:3000/users 
Content-Type: application:json

  {
    "id": ,
    "username": "Ahmadogo",
    "email": "ahmadogo@gmail.com",
    "password":"Ahmad@01",
    "walletAddress": "1234512345",
    "createdAt": "" ,
    "updatedAt": ""
  }